/**
 * Rótulos humanos para códigos `AuditLog.acao` e nomes de entidade.
 * Append-only: a UI de auditoria nunca edita/apaga — só traduz para leitura.
 */

export const AUDIT_ACAO_LABEL: Record<string, string> = {
  // Cadastro / membros
  CADASTRO_SOLICITADO: 'Solicitou filiação',
  RECADASTRO_SOLICITADO: 'Reenvio de cadastro',
  UNIDADE_CADASTRO_SOLICITADO: 'Solicitou cadastro de unidade',
  MEMBRO_APROVADO: 'Membro aprovado',
  MEMBRO_REPROVADO: 'Membro reprovado',
  MEMBRO_REVERTIDO: 'Aprovação revertida',
  MEMBRO_REVERTIDO_PENDENTE: 'Membro revertido a pendente',
  MEMBRO_LGE_ATUALIZADO: 'Cadastro LGE atualizado',
  MEMBRO_DESLIGADO: 'Membro desligado',
  MEMBRO_BLOQUEADO: 'Membro bloqueado',
  MEMBRO_DESBLOQUEADO: 'Bloqueio removido',
  MEMBRO_APAGADO: 'Cadastro apagado definitivamente',
  MEMBRO_SEDE_REATRIBUIDA: 'Unidade do membro alterada',
  MEMBRO_PENDENCIA_ESPELHO_SEDE: 'Solicitação espelhada na Sede',
  MEMBRO_SINCRONIZACAO_IGNORADA_JA_MEMBRO_DIRETO: 'Espelho ignorado (já é membro direto)',
  MEMBROS_IMPORTADOS: 'Base de membros importada',
  IMPORTACAO_DESFEITA: 'Importação desfeita',

  // Sócios
  CARTEIRINHA_EMITIDA: 'Carteirinha emitida',
  CARTEIRINHA_RENOVADA: 'Carteirinha renovada',
  CARTEIRINHA_REVOGADA: 'Carteirinha revogada',
  SOCIO_CARTEIRINHA_EMITIDA: 'Carteirinha emitida',
  SOCIO_CARTEIRINHA_RENOVADA: 'Carteirinha renovada',
  SOCIO_CARTEIRINHA_REVOGADA: 'Carteirinha revogada',
  SOCIO_NUMEROS_SINCRONIZADOS: 'Números de carteirinha sincronizados',

  // Eventos / sedes
  EVENTO_CRIADO: 'Evento criado',
  EVENTO_EDITADO: 'Evento editado',
  EVENTO_EXCLUIDO: 'Evento excluído',
  EVENTO_CHECKIN: 'Check-in em evento',
  SEDE_CRIADA: 'Sede criada',
  SEDE_EDITADA: 'Sede editada',
  SEDE_ATIVADA: 'Sede ativada',
  SEDE_DESATIVADA: 'Sede desativada',

  // Loja
  PRODUTO_CRIADO: 'Produto criado',
  PRODUTO_EDITADO: 'Produto editado',
  PRODUTO_ATIVADO: 'Produto ativado',
  PRODUTO_DESATIVADO: 'Produto desativado',
  CATEGORIA_CRIADA: 'Categoria criada',
  CATEGORIA_EXCLUIDA: 'Categoria excluída',
  CUPOM_CRIADO: 'Cupom criado',
  CUPOM_ATIVADO: 'Cupom ativado',
  CUPOM_DESATIVADO: 'Cupom desativado',
  PEDIDO_CRIADO: 'Pedido criado',
  PEDIDO_STATUS_ATUALIZADO: 'Status do pedido atualizado',

  // Bar (PDV)
  BAR_VENDA_REGISTRADA: 'Venda do bar registrada',
  BAR_VENDA_PIX_WEBHOOK: 'Venda do bar confirmada (PIX)',
  BAR_VENDA_PIX_CONFIRMADA_MOCK: 'Venda do bar confirmada (PIX mock)',
  BAR_VENDA_CANCELADA: 'Venda do bar cancelada',
  BAR_COMPRA_REGISTRADA: 'Compra de insumo do bar',
  BAR_PRODUTO_CRIADO: 'Produto do bar criado',
  BAR_PRODUTO_EDITADO: 'Produto do bar editado',
  BAR_PRODUTO_EXCLUIDO: 'Produto do bar excluído',
  BAR_CATEGORIA_CRIADA: 'Categoria do bar criada',
  BAR_CATEGORIA_EXCLUIDA: 'Categoria do bar excluída',
  BAR_BALANCO_ALTERADO: 'Visibilidade do balanço alterada',
  BAR_ESTOQUE_AJUSTADO: 'Estoque do bar ajustado',
  BAR_TURNO_ABERTO: 'Turno de caixa aberto',
  BAR_TURNO_FECHADO: 'Turno de caixa fechado',
  BAR_VENDA_ESTORNADA: 'Venda do bar estornada',
  BAR_FORNECEDOR_CRIADO: 'Fornecedor do bar criado',
  BAR_FORNECEDOR_EDITADO: 'Fornecedor do bar editado',
  BAR_FORNECEDOR_ATIVO_ALTERADO: 'Status do fornecedor do bar alterado',
  BAR_FIADO_REGISTRADO: 'Fiado do bar registrado',
  BAR_FIADO_QUITADO: 'Fiado do bar quitado',
  BAR_FIADO_CANCELADO: 'Fiado do bar cancelado',
  BAR_COMANDA_ABERTA: 'Comanda do bar aberta',
  BAR_COMANDA_ITEM_LANCADO: 'Item lançado na comanda',
  BAR_COMANDA_ITEM_REMOVIDO: 'Item removido da comanda',
  BAR_COMANDA_LIMITE_LIBERADO: 'Limite da comanda liberado',
  BAR_COMANDA_DESCONTO: 'Desconto na comanda do bar',
  BAR_COMANDA_FECHADA: 'Comanda do bar fechada',
  BAR_COMANDA_PAGAMENTO: 'Pagamento de comanda do bar',
  BAR_COMANDA_QUITADA: 'Comanda do bar quitada',
  BAR_COMANDA_CANCELADA: 'Comanda do bar cancelada',

  // Comunidade / moderação
  POST_CRIADO: 'Post criado',
  POST_ATUALIZADO: 'Post atualizado',
  POST_EXCLUIDO: 'Post excluído',
  COMUNICADO_CRIADO: 'Comunicado criado',
  COMUNICADO_ATUALIZADO: 'Comunicado atualizado',
  COMUNICADO_EXCLUIDO: 'Comunicado excluído',
  POST_SOCIAL_PUBLICADO: 'Post social publicado',
  POST_SOCIAL_EDITADO: 'Post social editado',
  POST_SOCIAL_EXCLUIDO: 'Post social excluído',
  POST_COMENTARIO_CRIADO: 'Comentário criado',
  POST_REPOSTADO: 'Post repostado',
  COMUNICADO_REPOSTADO: 'Comunicado repostado',
  POST_EVENTO_PUBLICADO: 'Post de evento publicado',
  POST_GRUPO_PUBLICADO: 'Post de grupo publicado',
  MOMENTO_STORY_PUBLICADO: 'Momento publicado',
  CANAL_TEMATICO_CRIADO: 'Canal temático criado',
  POST_CANAL_PUBLICADO: 'Post de canal publicado',
  PERFIL_DESTAQUE_CRIADO: 'Destaque de perfil criado',
  POST_DENUNCIADO: 'Post denunciado',
  DENUNCIA_RESOLVIDA: 'Denúncia resolvida',
  DENUNCIA_DESCARTADA: 'Denúncia descartada',
  DENUNCIA_MENSAGEM_RESOLVIDA: 'Denúncia de mensagem resolvida',
  DENUNCIA_MENSAGEM_DESCARTADA: 'Denúncia de mensagem descartada',
  NOTICIA_APROVADA: 'Notícia aprovada',
  NOTICIA_REJEITADA: 'Notícia rejeitada',

  // Acesso / governança
  ACESSO_USUARIO_ATUALIZADO: 'Acesso de usuário atualizado',
  ROLE_CRIADO: 'Cargo criado',
  ROLE_ATUALIZADO: 'Cargo atualizado',
  ROLE_EXCLUIDO: 'Cargo excluído',
  DEPARTAMENTO_CRIADO: 'Departamento criado',
  DEPARTAMENTO_ATUALIZADO: 'Departamento atualizado',
  DEPARTAMENTO_EXCLUIDO: 'Departamento excluído',
  DEPARTAMENTO_MEMBRO_ADICIONADO: 'Membro adicionado ao departamento',
  DEPARTAMENTO_MEMBRO_REMOVIDO: 'Membro removido do departamento',
  TENANT_PERFIL_ATUALIZADO: 'Perfil da torcida atualizado',
  TENANT_DISCORD_ATUALIZADO: 'Discord da torcida atualizado',
  TENANT_AFILIACAO_ATUALIZADA: 'Afiliação da torcida atualizada',
  TENANT_CRIADO: 'Torcida criada',
  OWNER_ATRIBUIDO: 'Presidência atribuída',
  OWNER_TRANSFERIDO: 'Presidência transferida',
  OWNER_REMOVIDO: 'Presidência removida',
  // Troca de gestão por `lib/lideranca.ts` — Caso B (cargo owner do tenant) e
  // Caso A (`Sede.responsavelUserId`).
  LIDERANCA_TRANSFERIDA: 'Presidência transferida',
  LIDERANCA_UNIDADE_TRANSFERIDA: 'Liderança da unidade transferida',
  LIDERANCA_UNIDADE_REMOVIDA: 'Liderança da unidade removida',

  // Alianças
  ALIANCA_PROPOSTA: 'Aliança proposta',
  ALIANCA_ACEITA: 'Aliança aceita',
  ALIANCA_REJEITADA: 'Aliança rejeitada',
  ALIANCA_ENCERRADA: 'Aliança encerrada',

  // Mensageria / salas
  GRUPO_CONVERSA_CRIADO: 'Grupo de conversa criado',
  GRUPO_MEMBRO_ADICIONADO: 'Membro adicionado ao grupo',
  GRUPO_MEMBRO_REMOVIDO: 'Membro removido do grupo',
  GRUPO_ADMIN_TRANSFERIDO: 'Admin do grupo transferido',
  MENSAGEM_DENUNCIADA: 'Mensagem denunciada',
  MENSAGEM_REMOVIDA_MODERACAO: 'Mensagem removida por moderação',
  USUARIO_BLOQUEADO_MENSAGERIA: 'Usuário bloqueado na mensageria',
  SALA_REUNIAO_CRIADA: 'Sala de reunião criada',
  SALA_REUNIAO_ENCERRADA: 'Sala de reunião encerrada',
  SALA_MENSAGEM_EDITADA: 'Mensagem da sala editada',
  SALA_MENSAGEM_EXCLUIDA: 'Mensagem da sala excluída',
  SALA_ENQUETE_CRIADA: 'Enquete criada',
  SALA_ENQUETE_VOTO: 'Voto em enquete',
  SALA_ENQUETE_ENCERRADA: 'Enquete encerrada',
  PERFIL_SOCIAL_ATUALIZADO: 'Perfil social atualizado',

  // Catálogo de clubes (`Afiliacao`) — ações de plataforma, sem tenant.
  CLUBE_CRIADO: 'Clube cadastrado',
  CLUBE_ATUALIZADO: 'Clube atualizado',
  CLUBE_ARQUIVADO: 'Clube arquivado',
  CLUBE_REATIVADO: 'Clube reativado',
  CLUBE_EXCLUIDO: 'Clube excluído',
  CLUBE_RIVALIDADE_ADICIONADA: 'Rivalidade adicionada',
  CLUBE_RIVALIDADE_REMOVIDA: 'Rivalidade removida',
}

export const AUDIT_ENTIDADE_LABEL: Record<string, string> = {
  SaasMembro: 'Membro',
  SaasSocio: 'Sócio',
  Evento: 'Evento',
  Sede: 'Sede',
  SaasProduto: 'Produto',
  SaasCategoria: 'Categoria',
  SaasCupom: 'Cupom',
  SaasPedido: 'Pedido',
  Post: 'Post',
  Announcement: 'Comunicado',
  Denuncia: 'Denúncia',
  Noticia: 'Notícia',
  Role: 'Cargo',
  Departamento: 'Departamento',
  Tenant: 'Torcida',
  Alianca: 'Aliança',
  Conversa: 'Conversa',
  Mensagem: 'Mensagem',
  SalaReuniao: 'Sala',
  User: 'Usuário',
  UserRole: 'Acesso',
  ImportacaoBase: 'Importação',
  PerfilMembro: 'Perfil',
  BarFornecedor: 'Fornecedor (Bar)',
  BarFiado: 'Fiado (Bar)',
  BarComanda: 'Comanda (Bar)',
  BarComandaPagamento: 'Pagamento de comanda (Bar)',
  BarVenda: 'Venda (Bar)',
  BarProduto: 'Produto (Bar)',
  BarCategoria: 'Categoria (Bar)',
  BarCaixaTurno: 'Turno de caixa (Bar)',
  BarMovimentacaoEstoque: 'Movimentação de estoque (Bar)',
  Afiliacao: 'Clube',
}

export function labelAcaoAuditoria(acao: string): string {
  return AUDIT_ACAO_LABEL[acao] ?? acao.replace(/_/g, ' ').toLowerCase()
}

export function labelEntidadeAuditoria(entidade: string | null | undefined): string {
  if (!entidade) return '—'
  return AUDIT_ENTIDADE_LABEL[entidade] ?? entidade
}
