/** Bandeiras oficiais dos estados (Wikimedia Commons — Special:FilePath). */
export const BANDEIRA_UF: Record<string, string> = {
  AC: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Acre.svg',
  AL: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Alagoas.svg',
  AP: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Amap%C3%A1.svg',
  AM: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Amazonas.svg',
  BA: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_da_Bahia.svg',
  CE: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Cear%C3%A1.svg',
  DF: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Distrito_Federal_(Brasil).svg',
  ES: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Esp%C3%ADrito_Santo.svg',
  GO: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Goi%C3%A1s.svg',
  MA: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Maranh%C3%A3o.svg',
  MT: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Mato_Grosso.svg',
  MS: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Mato_Grosso_do_Sul.svg',
  MG: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Minas_Gerais.svg',
  PA: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Par%C3%A1.svg',
  PB: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_da_Para%C3%ADba.svg',
  PR: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Paran%C3%A1.svg',
  PE: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Pernambuco.svg',
  PI: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Piau%C3%AD.svg',
  RJ: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_estado_do_Rio_de_Janeiro.svg',
  RN: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Rio_Grande_do_Norte.svg',
  RS: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Rio_Grande_do_Sul.svg',
  RO: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Rond%C3%B4nia.svg',
  RR: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Roraima.svg',
  SC: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Santa_Catarina.svg',
  SP: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_estado_de_S%C3%A3o_Paulo.svg',
  SE: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_de_Sergipe.svg',
  TO: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandeira_do_Tocantins.svg',
}
